name: tovuti_halmashauri
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: "0.12.0+2 "

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/coat_arms.png
    - assets/jafo.jpg
    - assets/kikwete.jpg
    - assets/magufuli.jpg
    - assets/majaliwa.jpg
    - assets/president.jpg
    - assets/suluhu.jpg
    - assets/waziri_mkuu.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Open Sans
       fonts:
         - asset: assets/fonts/OpenSans-Regular.ttf
         - asset: assets/fonts/OpenSans-Bold.ttf
         - asset: assets/fonts/OpenSans-Light.ttf
  #         style: italic
     - family: Eina
       fonts:
         - asset: assets/fonts/Eina01-Regular.ttf
         - asset: assets/fonts/Eina02-Bold.ttf
         - asset: assets/fonts/Eina02-SemiBold.ttf
         - asset: assets/fonts/Eina02-Light.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
